codium --install-extension abusaidm.html-snippets
codium --install-extension alefragnani.Bookmarks
codium --install-extension amiralizadeh9480.laravel-extra-intellisense
codium --install-extension bibhasdn.django-html
codium --install-extension bigonesystems.django
codium --install-extension bmewburn.vscode-intelephense-client
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension CoenraadS.bracket-pair-colorizer
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension esbenp.prettier-vscode
codium --install-extension felixfbecker.php-intellisense
codium --install-extension formulahendry.auto-close-tag
codium --install-extension geequlim.godot-tools
codium --install-extension Gruntfuggly.todo-tree
codium --install-extension Hridoy.adonisjs-snippets
codium --install-extension humao.rest-client
codium --install-extension martintheimer.nostromo-theme
codium --install-extension ms-python.python
codium --install-extension ms-vscode.cpptools
codium --install-extension octref.vetur
codium --install-extension onecentlin.laravel5-snippets
codium --install-extension ryannaddy.laravel-artisan
codium --install-extension sdras.vue-vscode-extensionpack
codium --install-extension sdras.vue-vscode-snippets
codium --install-extension shamanu4.django-intellisense
codium --install-extension tombonnike.vscode-status-bar-format-toggle
codium --install-extension vuetifyjs.vuetify-vscode
codium --install-extension wmaurer.vscode-jumpy
codium --install-extension xabikos.JavaScriptSnippets
codium --install-extension Zignd.html-css-class-completion
