code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bibhasdn.django-html
code --install-extension bigonesystems.django
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension geequlim.godot-tools
code --install-extension Gruntfuggly.todo-tree
code --install-extension Hridoy.adonisjs-snippets
code --install-extension humao.rest-client
code --install-extension martintheimer.nostromo-theme
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension octref.vetur
code --install-extension onecentlin.laravel5-snippets
code --install-extension ryannaddy.laravel-artisan
code --install-extension sdras.vue-vscode-extensionpack
code --install-extension sdras.vue-vscode-snippets
code --install-extension shamanu4.django-intellisense
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vuetifyjs.vuetify-vscode
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Zignd.html-css-class-completion
