codium --install-extension abusaidm.html-snippets
codium --install-extension adpyke.vscode-sql-formatter
codium --install-extension alefragnani.Bookmarks
codium --install-extension amiralizadeh9480.laravel-extra-intellisense
codium --install-extension aurorabiz.blade-ui-kit
codium --install-extension axosoft.gitkraken-glo
codium --install-extension bibhasdn.django-html
codium --install-extension bigonesystems.django
codium --install-extension bmewburn.vscode-intelephense-client
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension codingyu.laravel-goto-view
codium --install-extension CoenraadS.bracket-pair-colorizer
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension EditorConfig.EditorConfig
codium --install-extension esbenp.prettier-vscode
codium --install-extension fabiospampinato.vscode-diff
codium --install-extension felixfbecker.php-debug
codium --install-extension felixfbecker.php-intellisense
codium --install-extension firefox-devtools.vscode-firefox-debug
codium --install-extension formulahendry.auto-close-tag
codium --install-extension geequlim.godot-tools
codium --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
codium --install-extension ginfuru.vscode-jekyll-snippets
codium --install-extension Gruntfuggly.todo-tree
codium --install-extension Hridoy.adonisjs-snippets
codium --install-extension humao.rest-client
codium --install-extension itsjonq.owlet
codium --install-extension mikestead.dotenv
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-python.python
codium --install-extension ms-vscode.cpptools
codium --install-extension octref.vetur
codium --install-extension onecentlin.laravel-blade
codium --install-extension onecentlin.laravel-extension-pack
codium --install-extension onecentlin.laravel5-snippets
codium --install-extension ryannaddy.laravel-artisan
codium --install-extension sdras.vue-vscode-extensionpack
codium --install-extension sdras.vue-vscode-snippets
codium --install-extension shamanu4.django-intellisense
codium --install-extension shufo.vscode-blade-formatter
codium --install-extension Sophisticode.php-formatter
codium --install-extension streetsidesoftware.code-spell-checker
codium --install-extension streetsidesoftware.code-spell-checker-italian
codium --install-extension sumneko.lua
codium --install-extension tombonnike.vscode-status-bar-format-toggle
codium --install-extension VisualStudioExptTeam.vscodeintellicode
codium --install-extension vuetifyjs.vuetify-vscode
codium --install-extension wmaurer.vscode-jumpy
codium --install-extension xabikos.JavaScriptSnippets
codium --install-extension Zignd.html-css-class-completiocodium 
